version: "3"

services:
  webserver:
    build: 
      context: ./bin/centos
    container_name: 'cenos-webserver'
    restart: 'always'
    ports:
      - "80:8080"
      - "1935:1935"
    volumes: 
      - ./www:/mnt/
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
    